import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
Listner
a listner is an interface in java that listens some events generated by components.

ActionEvent fires on
>click on a button
>press enter in textField
>choose a menuitem

HOw to write an ActionListner
>ActionListner interface
>void actionPerformed()
addActionListner()
 */

class Nmyframw extends JFrame implements ActionListener {
    Container c;
    JButton button;

    Nmyframw()
    {
       c=getContentPane();
       button=new JButton("click me");
       button.setBounds(100,100,100,30);
       c.add(button);
       c.setLayout(null);
       button.addActionListener(this);

    }
    public void actionPerformed(ActionEvent e)
    {
      c.setBackground(Color.ORANGE);
      String str=button.getText();
      button.setText(str.toUpperCase());
    }
}
public class Swing14LActionListner {
    public static void main(String[] args) {
       Nmyframw f=new Nmyframw();
       f.setTitle("ActionEvent");
       f.setBounds(100,100,400,400);
       f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


       f.setVisible(true);
    }
}
